# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{structured_warnings}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gregor Schmidt"]
  s.date = %q{2009-11-28}
  s.description = %q{This is an implementation of Daniel Berger's proposal of structured warnings for Ruby.}
  s.email = %q{ruby@schmidtwisser.de}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "History.txt",
     "License.txt",
     "README.rdoc",
     "Rakefile",
     "lib/structured_warnings.rb",
     "lib/structured_warnings/dynamic.rb",
     "lib/structured_warnings/kernel.rb",
     "lib/structured_warnings/test.rb",
     "lib/structured_warnings/test/assertions.rb",
     "lib/structured_warnings/test/warner.rb",
     "lib/structured_warnings/warner.rb",
     "lib/structured_warnings/warning.rb",
     "structured_warnings.gemspec",
     "test/structured_warnings_test.rb",
     "test/test_helper.rb",
     "version.yml"
  ]
  s.homepage = %q{http://github.com/schmidt/structured_warnings}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Provides structured warnings for Ruby, using an exception-like interface and hierarchy.}
  s.test_files = [
    "test/structured_warnings_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.4.0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 1.4.0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 1.4.0"])
  end
end

